### PR TITLE
Embroider

### PR DESCRIPTION
**Pull request by evoactivity**
This seems to work in my app, want to see what happens in ember-try

### CODE REVIEW

**Comment by evoactivity** [comment]
I don't seem to be able to re-run tests, I think the ember-classic failure just needs to be re-run as it was fine in my commit before I turned on embroider-optimized (which is now green 🎉)

**Comment by rwwagner90** [comment]
@jherdman would it be possible to get this merged and released? I am also happy to help maintain this addon if you wanted to add me to the repo 😄

**Comment by jherdman** [comment]
Many many many thanks.

Resolves #230

**Comment by jherdman** [comment]
Released as 2.4.2

**Pull request merged**
