### PR TITLE
Fix missing assets

### LINKED ISSUE #233: 2.4.0 broken
I tried updating my app and none of my icons work and the asset viewer no longer loads. 

I don't know why yet.

At runtime I am warned `ember-svg-jar: Missing inline SVG for icon-name`.
There doesn't seem to be any packaged JS for the asset viewer?

edit: 
I wonder if it's down to embroider? Since the errors in the failing embroider-optimised scenario seem similar. Just don't know why 2.3.4 works but not 2.40.

### PR DESCRIPTION
**Pull request by bertdeblock**
Restores the public assets that were removed in https://github.com/voltidev/ember-svg-jar/pull/211.
Unsure if this is the right fix, but exactly these assets are still used in the `index.html` file:

- https://github.com/voltidev/ember-svg-jar/blob/master/packages/ember-svg-jar/public/index.html#L107
- https://github.com/voltidev/ember-svg-jar/blob/master/packages/ember-svg-jar/public/index.html#L204
- https://github.com/voltidev/ember-svg-jar/blob/master/packages/ember-svg-jar/public/index.html#L205

Closes #233.

### CODE REVIEW

**Comment by bertdeblock** [comment]
@jherdman Would you mind giving this a review? The icon viewer is broken in `v2.4.0` in both classic and Embroider builds.

**Comment by jherdman** [comment]
Many thanks for the fix! I'll put together a release right now.

**Comment by bertdeblock** [comment]
Thanks for the release @jherdman!

**Comment by tdwesten** [comment]
yeah @jherdman thanks!

**Pull request merged**
