### PR TITLE
feat: Add typing for glint

### PR DESCRIPTION
**Pull request by muziejus**
This commit adds two files that can be read by Ember apps using glint so that they can benefit from glint's type-checking.

I think I have included all of the possible named attributes that can get passed to the `{{svg-jar}}` helper.

To wit:

```ts
interface SvgJarAttrs {
  width?: string;
  height?: string;
  class?: string;
  role?: string;
  title?: string;
  desc?: string;
}
```

### CODE REVIEW

**Comment by jherdman** [comment]
Oof... I'm really sorry I didn't see this sooner. I'm not presently using Glint in any of my projects. Is someone available to test this out?

**Review by jherdman — APPROVED** [review]
I'm going to merge this. I'm hoping that if there are issues with this in a forthcoming release users of Glint will send patches.

Many thanks for your work! ❤️

**Comment by langalex** [comment]
Is there anything I have to do for glint to pick up the type definitions? If I copy the defintions you added into my project, everything works, but without it, nothing. cc @muziejus

**Comment by SergeAstapov** [comment]
@langalex yes, you need to import definitions like described in https://typed-ember.gitbook.io/glint/using-glint/ember/using-addons#using-glint-enabled-addons

**Comment by langalex** [comment]
@SergeAstapov thanks, and apologies. I should have spent some more time reading before asking.

I ended up just adding this…

```ts
import type from 'ember-svg-jar/glint';
```

… since [the types file](https://github.com/voltidev/ember-svg-jar/blob/master/packages/ember-svg-jar/types/glint.d.ts) does not export a type but already extends the registry.

**Comment by SergeAstapov** [comment]
@langalex yeah, this PR landed before latest changes in Glint, which were proposed/discussed in https://github.com/typed-ember/glint/issues/439

**Pull request merged**
