### PR TITLE
use guidFor to create unique id's

### LINKED ISSUE #222: Title ID's should be unique
#### Describe the bug

An svg using `title` and `desc` will result in tags with id's of `title` and `desc` which is used by aria-labelledby. Using more than one svg with a title on a page results in multiple `title` id's on the page. 

#### Expected behavior

Each SVG would use a unique ID

#### Possible Solution

Could `guidFor` be used to generate a unique ID for the svg instance?
https://api.emberjs.com/ember/4.2/functions/@ember%2Fobject%2Finternals/guidFor

#### Screenshots

image

### PR DESCRIPTION
**Pull request by evoactivity**
This will create a unique ID for the title and desc tags using ember's guidFor method.

Fixes #222

### CODE REVIEW

**Comment by jherdman** [comment]
@evoactivity my apologies for sleeping so long on this PR. Are you amenable to rebasing this work? It doesn't merge well at this time.

**Comment by evoactivity** [comment]
I'll take a look at the failing tests locally when I have a little more time, I've gotten as far as I can editing directly on github lol

**Comment by jherdman** [comment]
Some of them are expected. I can make a list tomorrow. I ought to post them
as known issues in case anyone wants to take a crack at them

**Comment by evoactivity** [comment]
I've made some changes and now the tests are passing locally.

**Review by jherdman — APPROVED** [review]

**Comment by jherdman** [comment]
Rerunning...

**Comment by evoactivity** [comment]
All failures in ember-try scenarios are looking for `patch-package` but it doesn't exist, but I don't really know why?

**Comment by jherdman** [comment]
Well, I have no idea why this was failing. Everything but embroider-optimized is green and this is a known issue.

Many thanks for your work!

**Pull request merged**
